export const sounds = {
  C2: require('../../assets/sounds/piano/C2.wav'),
  Db2: require('../../assets/sounds/piano/Db2.wav'),
  D2: require('../../assets/sounds/piano/D2.wav'),
  Eb2: require('../../assets/sounds/piano/Eb2.wav'),
  E2: require('../../assets/sounds/piano/E2.wav'),
  F2: require('../../assets/sounds/piano/F2.wav'),
  Gb2: require('../../assets/sounds/piano/Gb2.wav'),
  G2: require('../../assets/sounds/piano/G2.wav'),
  Ab2: require('../../assets/sounds/piano/Ab2.wav'),
  A2: require('../../assets/sounds/piano/A2.wav'),
  Bb2: require('../../assets/sounds/piano/Bb2.wav'),
  B2: require('../../assets/sounds/piano/B2.wav'),
  C3: require('../../assets/sounds/piano/C3.wav'),
  Db3: require('../../assets/sounds/piano/Db3.wav'),
  D3: require('../../assets/sounds/piano/D3.wav'),
  Eb3: require('../../assets/sounds/piano/Eb3.wav'),
  E3: require('../../assets/sounds/piano/E3.wav'),
  F3: require('../../assets/sounds/piano/F3.wav'),
  Gb3: require('../../assets/sounds/piano/Gb3.wav'),
  G3: require('../../assets/sounds/piano/G3.wav'),
  Ab3: require('../../assets/sounds/piano/Ab3.wav'),
  A3: require('../../assets/sounds/piano/A3.wav'),
  Bb3: require('../../assets/sounds/piano/Bb3.wav'),
  B3: require('../../assets/sounds/piano/B3.wav'),
};
